/**
 * Generated by endpoints-angular-client-generator (version 0.0.1-5)
 * Arguments:
 *   endpoints-angular-client-generator -s -d /Users/krico/Projects/trocado/target/generated-sources/appengine-endpoints/WEB-INF/expense-v1-rest.discovery -o /Users/krico/Projects/trocado/src/main/client/endpoints
 */
/*global angular*/
(function (angular) {
    'use strict';
    angular.module('expense.endpoint', ['ng']);
}(angular));
